/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Encrypt and write a seed into the 4-shard layout.
 * Call this once during initial setup / provisioning.
 *
 * Creates:
 *   <config_dir>/seed.enc    (shard_A: AES-GCM encrypted seed)
 *   /var/lib/aawp/.cache/fonts.idx  (shard_C: 16 random bytes)
 *
 * shard_B is embedded in the binary at link time (.init section).
 * shard_D is computed from the binary hash — no file to write.
 *
 * SECURITY: Seed is generated INSIDE Rust via OS CSPRNG. It never crosses
 * the NAPI boundary, never touches JS memory, and is zeroized immediately
 * after encryption. The only output is shard_B (for ELF injection).
 *
 * To extract the seed, an attacker must:
 * 1. Modify this Rust source → recompile → but binary hash changes → shard_D
 *    changes → old seed.enc becomes undecryptable (self-referential integrity)
 * 3. Read /proc/pid/mem → seed only exists unmasked for <1ms (Layer 2 XOR mask)
 *
 * Returns shard_B bytes so the caller can inject into the ELF build.
 */
export declare function _p0(configDir: string): Buffer
/**
 * Compute a SHA-256 hash of a file's contents.
 *
 * Compute logicHash = SHA256(aawp-core.node || index.js).
 * Covers the skill's runtime: Rust binary + JS loader. Nothing else.
 * Contracts belong to the protocol; scripts belong to the user.
 * Returns `0x` + hex-encoded SHA-256.
 */
export declare function _c0(codePath: string): string
/**
 * Get the SHA-256 hash of the .node native module itself.
 * SHA-256 of the running .node binary. Cached after first call (~450ms → <0.01ms).
 */
export declare function _b0(): string
/**
 * Check if this build has an expected hash baked in (release mode).
 * Returns the expected hash string, or empty string if dev mode.
 */
export declare function _e0(): string
/** _x0: Return the computed socket path (for JS loader to connect). */
export declare function _x0(): string
/**
 * _a0: Return the current AI gate token (hex, 64 chars) for OpenClaw to inject
 * into child processes via AAWP_AI_TOKEN env var. Returns empty string if gate disabled.
 * OpenClaw must call this right before spawning wallet-manager.js.
 * _i0: Lightweight init for wallet-manager.js client mode.
 * Sets config_dir so that _h0 (HMAC) and _x0 (socket path) work correctly.
 * Does NOT start a daemon thread, does NOT acquire locks.
 * wallet-manager.js uses this to connect to the persistent daemon started by OpenClaw.
 */
export declare function _i0(configDir: string, skillDir: string): void
export declare function _a0(): string
/** _h0: Compute HMAC for a given timestamp (for client auth). */
export declare function _h0(ts: number, configDir?: string | undefined | null): string
export declare function _l0(configDir: string, skillDir: string, logPath: string): void
