#!/usr/bin/env bash
# init_collab.sh — Initialize collaboration workspace structure
# Usage: ./init_collab.sh /path/to/project

set -euo pipefail

PROJECT_DIR="${1:-}"
if [ -z "$PROJECT_DIR" ]; then
  echo "Usage: $0 /path/to/project"
  exit 1
fi

SHARED_DIR="$PROJECT_DIR/shared"

mkdir -p "$SHARED_DIR"

# Create .gitignore to keep build artifacts out
if [ ! -f "$PROJECT_DIR/.gitignore" ]; then
  cat > "$PROJECT_DIR/.gitignore" << 'GITIGNORE'
# Agent Collaboration Protocol
shared/build-*/
GITIGNORE
  echo "[OK] Created .gitignore with build directory exclusion"
fi

# Create template SPEC.md
if [ ! -f "$SHARED_DIR/SPEC.md" ]; then
  cat > "$SHARED_DIR/SPEC.md" << 'SPEC'
# SPEC: {Feature Name}

> Generated by Agent Collaboration Protocol

## Overview

One sentence. What this feature does and why it matters.

## Contract

| Field | Value |
|-------|-------|
| API Base Path | `http://localhost:8000/api/v1` |
| Auth Scheme | Bearer JWT |
| Content Type | `application/json` |
| Error Format | `{ "error": "...", "detail": { ... } }` |

## Endpoints

### `GET /api/v1/{resource}`
**Response:** `200 OK` with data array

### `POST /api/v1/{resource}`
**Response:** `201 Created`

## Success Criteria

- [ ] Observable behavior that proves it works
SPEC
  echo "[OK] Created shared/SPEC.md template"
fi

echo ""
echo "=== Collaboration workspace initialized ==="
echo "  Project: $PROJECT_DIR"
echo "  Shared:  $SHARED_DIR"
echo ""
echo "Next: Edit shared/SPEC.md with your feature contract,"
echo "then spawn backend and frontend agents."
